---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: admin-password-hash
  namespace: ccl
spec:
  encryptedData:
    ADMIN_PASSWORD_HASH: AgBUQ5yo00CuhiHtI4yLGgagwOjfTXoWSDBAJXFsIqy+WOgIHJiEk9koPdoG8/LNnqN3mwNUwWSi2e8AF3WbiLoqVazKFRvbqlRrMHAH4B2zP676v8Tgyqf4NmV0nJBiUo2ZjwV3PrTxLNyMnkOn5yiNZLpoCKFzzZF/PR+/ObkI1EOgXOjX37md9BOBfRoguiI3V6pp5+KBGSDgBaJSbKdDS2uJyFDdXadoOzXzPBahnWyfgkxjJo9qRv2BAlJ8/d8nUIDkJZ0cSI8DFCDlf/Qu6gnJkFmu/cOPJRUe/7fur7WPXL7a4OYWfTbaacEpOcKck4Yr2Nq6VYxISfTqDDpwm90MlL3PVFU4W+ucka2l23tI4oGTPmUmFqtu4PEa0WjAkQJx24r/1U8ZYV35bxXifoxH+LyHad2892Kob/37Kwn15IM3j5gEBn3SfDXNZYDBPunofOG3ABoLxq63ppWpTHOHnItCYxl2Mog3fiQBeuaxhgy4SbBmJZN6WSjGAJj0poenwWMYulj3YNgMIYW3YgcnjvaEEZo6/Wldyxzbl04BnT5kTC6EuXbgC3AwZ4vQErLvbMPUo2V20jQ4fW6Hq03wuGApmreH3wAUk/wa0ZvBNkyKySR6uUbY9QlgXSswTQzOCTPqp65I2Nc/w4cyGQsrqwB503GS3iqk1jKlh7/+CybTMXn19H2XJ30wHZfXq/0PzqfXm5d2khfSRWDq8kDJiL6rFnrq2rKPTh+D8WKTVAijkDjOao3e6OCy6rQyt2cIUkvIHq/1SMEXowe7czKVnhj2BlgnPSUxFk3VsF/t++D4iQz3cCtb2pczfTdP2LdApAMmAA==
  template:
    metadata:
      name: admin-password-hash
      namespace: ccl
