---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: admin-password-hash
  namespace: ccl
spec:
  encryptedData:
    ADMIN_PASSWORD_HASH: AgCXpDTB5cuzam7i+bcSmcXYgTPA7tycjnv+JUJwoE2fcHzp9Y+D0eg/VDBVPshwsOcarxBIjuwo7RT8CCbGwRe6a5C7Qj0anmlRZzdUhJvxnWC86GuWhff5q/JMMo4fscO8PLOKjqo/5NNSBcokKpINaxWDO2SumNZcnHbx8xryzWLNqXliMw1yg9kdxNpe98WzFBFZw+PxvJlu+qvrkpfmfZNGDrJnuOflounzVNHc3fmMSK2C9JWLSvq6sdpt7i2rxUX8kmv3YWr/dfZv8PRboEgvxi4EvKhRkgqQ1ve4hBli6ixRdv1pUb/VuTb/1Y2NZh+HHoBbG6vg+LEYx4CsfQOkN1cD0T2Q5bPGhLXwsBJv+t2tSjOlsqyFbz4usYjswaqXmGtJbW2Kyfzrwr446Gg4OILS9shYE0a12DoTInFpYhBWK/+GLEci5f9UCB50WtgPodC8FAfEK2tyYUaoT9jkC54GI8WGoipRotQanCCkmrLRHiPdDkb8RpRv0o8YnFD6Js9fW0pPFC+GrbcpD7Cxrh5Bww46lRSw2vWv8kVRI9dVi5LSWjTkp5zXKM/v+0acMjuQmIo2rG199D+5Jjh8Is1tarDufsk0xaHy45CYpzrwI1Gz5SyasdvMKYu4f21RBci4CIogv8jd2SSVYvqzCFNjZvoc/oyYknrciBim49wkLfeZ5u5PLU5au83d0oeFxkXAYM5G46+HsguSssejYzgSyBBbnbZ1L2sF8mauuPMv3HJ6pRs0CfVlNEE3Kaq3j+/93Ugwv88ZO9tqU2DL809o4oJKP3fa8h6NQTMYKXaiy7jKnT5EyNaToSI8EhaShDLYng==
  template:
    metadata:
      name: admin-password-hash
      namespace: ccl
