---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: blog-admin-token
  namespace: ccl
spec:
  encryptedData:
    BLOG_ADMIN_TOKEN: AgASVqYgIxbmaTkjWiqeVUXzSsiDAs9SgMUMPjJK8/6PJNxzTYWf4yRlX/t64R7JN60Kfeuq/I526NUdLinCwJ3kdRiLWTsPFznJ0G1TSUk5tcEMmsFenL4ZS2QqJBxRBiucbjGKBAfzZo91bvfYTbFwb55VWNNu62zMRe/JW6Xrgi1znA8y8FQ9ADqgowafVC0UWEWr+bnmRNxlo8cGinLnP2uHZG1ralBEolg8hd0P3irzaBOdzByw/Fg0RD6kEZGki6DLLUsKTBRHPo14jmS2yK6emIPeghu/HMNamUHvPm1QjWipxgAOKyNPs1aVF2P4Ud32x8vUJJBBPd4gpIvLlNz1/25herX1XrzK2yAyODD1ET2xoMukNkAb71EUH7ZQDKvm3V/pCJ3+xF/Lc4Y9K4eV4/pEr0rSzBCzavH1vMz9l46RN2JPLrf1KYuURxgKh3aa98Jm9OnWY1IxS6+ArXU1ICup9aKS7am8vgwj/C09B8e199fpArgSJxMcui0y9GIdMoaioZxPDtyk/8s1TRiulvZHcR7bNwpmjW+JhcNCzt+d1EyffAjj+QfSirb4zwzHg+i/A9SarmK2/LVpaBOpINt0rS+KCCKtD9Lbv9mQIERTmJPVgwIYnXT8kDUNRzswgxyHu6F7GSr/dj+/DVuBhjxaPErFLHgXRZwR9/AgEk+Em0Ke0UhZZrpXV/ubXe0USdL4mlP5QO4o/64B7kB/VD67Wodgnsp+tlkppytzOQnDV+kzSEEidSysFu3sY2WPXiWLVVhashYcoKWB
  template:
    metadata:
      name: blog-admin-token
      namespace: ccl
