---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: blog-admin-token
  namespace: ccl
spec:
  encryptedData:
    BLOG_ADMIN_TOKEN: AgBUhpal32TTDM/g/9lZOojGDfXtqA8W6PdCrmtnD79zKKajROiDd2sCH1lAAaDPP4Gap88tJac48XOxcjrwnUJ7O1m0Crfs2FhokotS2R/UCD7ObZzKCeH7J863J36xDXk/0BW2TMVqHhHG39XJexOWh8abgRdT2ZEUItyg1A6Hq3Atc6r776hAr9o0KowJKWYu9fic4CLl8T+fF1/SqgHsFyR4OkXtLCvkOpsvgW/eLiQttv5wA45/Ro/54CIj6UUOjjBmwtAKq4gR1Kw4ovCctf+CUGlNTAJBwqNrjzZinGhGkOpJacLjqJYbPMeQKEPp6/Zdf62iDymHE2U0dYt4fZTLiy9LuesLFMI5EAFX5ATXG8yJ9oaLd7JsVU4j6riMmzwR4rmfyhtnmBcv4wAzZrulRl5MM7rb9KoHTnC9Ewqbds3LVfIg9oyVVwPXQ8wMFs1sP9pebB383sULur5OWb6Eyq0Fg2CueGo57Ar9HvJ9g5AZHuTrzIjNADez4fok8wDcmRQyePYbT7DiEbaWvOWzmHZ/5KUWwdHOgt6OJ/0H4XyfvEHOdYAMA1FHhyliWn9GzG7RaS/pVLX8YMhu0roLZsPustjVDgsGrp812aYamgEqqNe6YbnxaoECSI9to4xV4NVnlTwVlnefAW1KLol5aSQ1g4xSwLOibM4mOjvSDv19eElwqL6H0SMrKOLP5zv1vlhu3E5S2QM2of3p3IaBp1d7jurgnf0AMpATh5lpq3xQMDXnEXOqIdG4rjvw+tZ/Kmggg6aYX9I/zvng
  template:
    metadata:
      name: blog-admin-token
      namespace: ccl
