apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ccl
resources:
  - namespace.yaml
  - postgres-sealed-secret.yaml
  - blog-admin-sealed-secret.yaml
  - url-shortener-sealed-secret.yaml
  - postgres.yaml
  - backend-api.yaml
  - url-shortener.yaml
  - web-app.yaml
  - ingress.yaml
