---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: session-secret
  namespace: ccl
spec:
  encryptedData:
    SESSION_SECRET: AgBDpNL76K/B562gXKUICP3P/49oU7o8KWHZ100EEf49TtrjTvwXFzhn1HSuDcYyA+ywNa+bWl2ZSEcVgIybdIscEjvQ29AlZ5Ka1FOp++Dj9buMiaUypbfnWA2ZnaSsYlNgj7BE+bv+1g4cRO0fzkbn/yRsiiYGoAaYKNlDMI13c5bhsZqIA46D/j3S3o5DVHzcmVXNKVSzCdxwBW52y/1KUOGN46QZSDduT/aw1GPT6gsozLzxhB8K6oMVpGL6OK1kFuUTu74m1LenvXz+laoDdbt4bm82I4EmhPFzk48XCiAe8eP3r4/grfOvmQrV5s6d3yHzIPvBtuXq6U+KA7t4SWRMM5MV0Cl+51Hw0GT0v5RzdCiO9phRRLkI4Wvt+JFUdcPUJyEyNRKtqXM6Ur12AxgDT/06Yg/+GxdBZnVlok660/Kzn/ZEUOsxiSZn57/NAdBu1FqJJpHhuv0aDAyAm63PThHOQ2uxRBMyBEo2VoMrCrMQo5A4XokhEYlMmM5jMQkUwkZHqZ25OBK6kAokF7vlPeNCsnmfVxI9pRi6U+AGyBkfhdlxbYtCzzqYED8Q0Jwxf7rhvdQm4Xg1iABi743hWioTIWwsNVACVghXcrl7vPQM4vG0xSXQIaWjH3f5jDdKw32L/jfyXIz/WsVRvwq9lKCgu91w94F+U3HU7RvVVbeowiZ1bcgAnmyJn7CcwtGd3DXaL3Zr85jnUAy2ToqFMt7DbqJWNwx+hEhgCoIEBcL9q3BvJbF28NdI+kRe4YSxisdY3VN1j903VAjf
  template:
    metadata:
      name: session-secret
      namespace: ccl
