---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: url-shortener-admin-token
  namespace: ccl
spec:
  encryptedData:
    URL_SHORTENER_ADMIN_TOKEN: AgCGqAk0yasU1okPdB80QLrlzd6sZRl6sqLzom/VmOmf85RccK1R4/mmsikHAZlWnj9kJbMuIcirPYoXI8COfclOP/hw/KwOi3YIDifGvaLq+vLjvLJsqnXKPbAnZFn3ut7GXSc80DUnX4EbENJgeBGcVRtx1rmARnBUdRlCEJZq3TSGVOPArE5KCBRP+AdigFj1dzYuRBStdMZVj/tgCaz0fYpxmaR21i33DXgSOn6OotD77n/tDcc0ybYhMrFYx3sBUhJcKpfd23SfJgnxl41OyNbnKM4tXz9yJdQagYWKACgSvO3GAIRglWcjd2YcgyiWdv60CXucyxqEun1bNUDO59UgkS7Ejr1yhqIXcDofwuxS/FJdfXZcfOdw4gLCyj/Kld5GDmNPibb+FVi9PlrnMVXOJveuY2hMT1o278WqN42eOuM46yRNRMrFC5suDIqCAKH4t71ZgzGM6RWAy9K7g2JF+uwUCMwZR0Exm9sEJKC3TZrjcjkAchE5VTG4ETpBhVb1rnpFA5++WAaDTC8s8s4xg9YhdsgcW9kVjttCQ+4Rilr1z31sdllVpo8yngYb+zXoUO6gF2J6K4gRzlJ4ev1tlMw0ycPj4J0sl6NULSbwHi8pnVApcZZZZxV5ol6KCPZ4D+EMLe4zdJgOWXGsLU/LhnMCHRPQLh2U6ui13pes2jQHA0AzWZWkbDF/yyia3ovKn9b/cYuR04O66lOR7Wcw5czCjDTSy5E5ciD/esRb7Ms=
  template:
    metadata:
      name: url-shortener-admin-token
      namespace: ccl
    type: Opaque
