---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: url-shortener-admin-token
  namespace: ccl
spec:
  encryptedData:
    URL_SHORTENER_ADMIN_TOKEN: AgAIFzKiCAhDnk+8VvEi7x6YtbhImro3qN+n+CU2gBNrSVHSC16j5hsfUybCcQwafThm+STMKl8w407Y8hGT5XgZXgBXfIpbmBRmJjdyXzTT7uVBYQUlNPqIdue4gyO8EtAkvkZgQIFlRJQoem9jSyEf/6WKV+A/5yNhB0yHxe+PDvHepAHuV6C1nruFsjH3mW2crBCCLqXT7ErC7HuBUjsqZBJ4c3R2HTYeujAhGcPifBqqX/eUH1ZYhNZd9zuwysQk+5DREMrpp3KqWYVTOIUukq7XE2Lba4i2NM2ANxMpOvW4CowQ7Sjl9GAfwrigyAfGSEWTp3U1qHL1VFtQeiWG2cw8IaNtR8RVYxb/LRvjTv3J+x2vguDDmkErubrv+80fAen/BTMfLt3Cq+avjjdF4Ep2SZW05qkWsHWKdhYUQLEoc+DC+wtf3DLiA5l874ueeU1BLw84SSEf3Dn4ggxc773TqzZJByk4G3vx+OP8NpRGFnhreBCkaRNAK2VUXGrQ3C7JA31Ws5/Vqg6M+6YrFtqmtr/DoVxRwz0naHrJzs6CfPbUfvrZsXORFTZej7JxM69hOglHiQWwLo4U57TiTqehlkSs0ckBRXgd6oWahTRiHqtcKLIbjl1yB/BsQdNrpWJBUZdaBD67HgD6KM+R5VjwHPatgimp9jJ6jlCNGCLGvQrTRlUbOfgx9nPTg9IXPtpJVxnpw7Oxe+uQfcj5SLWqEBg3NICXv+COZ+nLEaEky35C+TfHdDUxHNjolzyQRYcFXmqGcHy1UuioFaOI
  template:
    metadata:
      name: url-shortener-admin-token
      namespace: ccl
